name: subject_lift_kit
description: "A new Flutter plugin project."
version: 0.0.1
homepage: https://github.com/tttocklll/subject_lift_kit

environment:
  sdk: ^3.8.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^26.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: SubjectLiftKitPlugin
